# Generated by Django 4.2.6 on 2025-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="平台名称"
                    ),
                ),
                ("url", models.URLField(verbose_name="访问链接")),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="简介说明"),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="访问量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "AI平台",
                "verbose_name_plural": "AI平台管理",
            },
        ),
    ]
