# Generated by Django 4.2.6 on 2025-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplatform",
            name="order",
            field=models.IntegerField(default=0, verbose_name="顺序"),
        ),
    ]
