# Generated by Django 4.2.6 on 2025-03-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_aiplatform_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiplatform",
            options={
                "ordering": ["order"],
                "verbose_name": "AI平台",
                "verbose_name_plural": "AI平台管理",
            },
        ),
    ]
